Repository UQcsse3200/2025-studio-3, pull requests merged in 2025-10, with the labels that each got.

#277 Task/level preview
  ai/team7.md
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/entities/EntitySpawn.java
  source/core/src/main/com/csse3200/game/entities/WaveConfigProvider.java
  source/core/src/main/com/csse3200/game/entities/factories/RobotFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/WaveService.java
Labels: sprint 3, team 7

#265 Task/robot animation improvements
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/npc/RobotAnimationController.java
  source/core/src/test/com/csse3200/game/components/CombatStatsComponentTest.java
Labels: sprint 3, team 6

#257 Feat/human extension: Army Guy Entity and Shadow Entity
  source/core/assets/configs/defences.json
  source/core/assets/images/effects/bullet.png
  source/core/assets/images/effects/shock.png
  source/core/assets/images/entities/defences/army_guy_1.png
  source/core/assets/images/entities/defences/machine_gun.atlas
  source/core/assets/images/entities/defences/machine_gun.png
  source/core/assets/images/entities/defences/shadow.atlas
  source/core/assets/images/entities/defences/shadow.png
  source/core/assets/images/entities/defences/shadow_idle1.png
  source/core/assets/images/entities/defences/wall.atlas
  source/core/assets/images/entities/defences/wall.png
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/DefenderStatsComponent.java
  source/core/src/main/com/csse3200/game/components/ProjectileComponent.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/currency/CurrencyGeneratorComponent.java
  source/core/src/main/com/csse3200/game/components/currency/CurrencyInteraction.java
  source/core/src/main/com/csse3200/game/components/dossier/DossierDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/DefenceAnimationController.java
  source/core/src/main/com/csse3200/game/components/projectiles/MoveDirectionComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/AttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/IdleTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TargetDetectionTasks.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseDefenderConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/DefenceFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/GeneratorFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/progression/arsenal/Arsenal.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/DefenderStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/AttackTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/IdleTaskTest.java
  source/core/src/test/com/csse3200/game/progression/arsenal/ArsenalTest.java
Labels: sprint 3, team 2

#282 Item Config Update
  ai/team8.md
  source/core/assets/configs/items.json
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseItemConfig.java
  source/core/src/test/com/csse3200/game/areas/LevelGameAreaTest.java
Labels: enhancement, sprint 3, team 8

#296 Task/diff levels to feat/levels-extension for #234 #235
  source/core/assets/configs/levels.json
  source/core/assets/images/backgrounds/level-1-map-v1.png
  source/core/assets/images/backgrounds/level-1-map-v2.png
  source/core/assets/images/backgrounds/level-2-map-v1.png
  source/core/assets/images/backgrounds/level_map_final.png
  source/core/assets/images/backgrounds/level_map_grass.png
  source/core/assets/images/backgrounds/level_map_town.png
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/areas/SlotMachineArea.java
  source/core/src/main/com/csse3200/game/components/slot/SlotMachineDisplay.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
Labels: sprint 3, team 7

#294 Level win condition functionality added
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/LevelCompleted/LevelCompletedWindow.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/components/LevelCompletedWindow/LevelCompletedWindowTest.java
Labels: sprint 3, team 7

#303 Task/lga cleanup and refactoring #274
  ai/team7.md
  source/core/src/main/com/csse3200/game/areas/ItemHandler.java
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/areas/WavePreviewManager.java
  source/core/src/test/com/csse3200/game/areas/LevelGameAreaTest.java
Labels: sprint 3, team 7
