Repository UQcsse3200/2025-studio-3, pull requests merged in 2025-09, with the labels that each got.

#70 merging main into enemy branch
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/data/MenuSpriteData.java
  source/core/src/main/com/csse3200/game/data/MenuSpriteDataBuilder.java
  source/core/src/main/com/csse3200/game/data/MenuSpriteDataEditor.java
  source/core/src/main/com/csse3200/game/exceptions/MenuSpriteNotFoundException.java
  source/core/src/main/com/csse3200/game/screens/DynamicMenuSpriteScreen.java
  source/core/src/main/com/csse3200/game/screens/MenuSpriteScreen.java
  source/core/src/main/com/csse3200/game/services/MenuSpriteService.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/data/MenuSpriteDataBuilderTest.java
  source/core/src/test/com/csse3200/game/data/MenuSpriteDataEditorTest.java
  source/core/src/test/com/csse3200/game/data/MenuSpriteDataTest.java
  source/core/src/test/com/csse3200/game/services/MenuSpriteServiceTest.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
Labels: sprint 1, team 6

#71 merging grid_system into enemy branch
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/areas/LevelGameGrid.java
Labels: enhancement, sprint 1, team 6

#100 Merging Feat/enemy into main
  source/build.gradle
  source/core/assets/configs/NPCs.json
  source/core/src/main/com/csse3200/game/GdxGame.java
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/HitMarkerComponent.java
  source/core/src/main/com/csse3200/game/components/currency/CurrencyGeneratorComponent.java
  source/core/src/main/com/csse3200/game/components/currency/SunlightComponent.java
  source/core/src/main/com/csse3200/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/csse3200/game/components/npc/DespawnOnPlayerContactComponent.java
  source/core/src/main/com/csse3200/game/components/npc/RobotAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/MoveLeftTask.java
  source/core/src/main/com/csse3200/game/components/tasks/MovementTask.java
  source/core/src/main/com/csse3200/game/components/tasks/WanderTask.java
  source/core/src/main/com/csse3200/game/entities/Entity.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseEntityConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/FastRobotConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/StandardRobotConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/TankyRobotConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/DefenceFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/NPCFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/RobotFactory.java
  source/core/src/main/com/csse3200/game/physics/components/PhysicsMovementComponent.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ServiceLocator.java
  source/core/src/test/com/csse3200/game/areas/SpawnRobotTest.java
  source/core/src/test/com/csse3200/game/components/DespawnOnPlayerContactComponentTest.java
  source/core/src/test/com/csse3200/game/components/HitMarkerComponentTest.java
  source/core/src/test/com/csse3200/game/components/TouchAttackComponentTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MoveLeftTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MovementTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/WanderTaskTest.java
  source/core/src/test/com/csse3200/game/services/ServiceLocatorTest.java
Labels: sprint 1, team 6

#147 Issues #129 Tile cleanup, #114 Screen resize bug fix and #116 Coordinate system refactor
  source/core/src/main/com/csse3200/game/areas/AreaAPI.java
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/areas/LevelGameGrid.java
  source/core/src/main/com/csse3200/game/components/InventoryUnitInputComponent.java
  source/core/src/main/com/csse3200/game/components/tile/TileInputComponent.java
  source/core/src/main/com/csse3200/game/components/tile/TileStatusComponent.java
  source/core/src/main/com/csse3200/game/components/tile/TileStorageComponent.java
  source/core/src/main/com/csse3200/game/entities/factories/GridFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/test/com/csse3200/game/tile/TileTest.java
Labels: bug, sprint 2

#172 Add Teleportation Robot Enemy and Unit Tests
  source/core/assets/configs/enemies.json
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/tasks/MoveLeftTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TeleportTask.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/TeleportRobotConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/RobotFactory.java
  source/core/src/main/com/csse3200/game/physics/components/ColliderComponent.java
  source/core/src/test/com/csse3200/game/components/tasks/MoveLeftTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TeleportTaskTest.java
  source/core/src/test/com/csse3200/game/tile/TileTest.java
Labels: sprint 2, team 6

#195 Feat/enemy
  ai/team6.md
  source/core/assets/configs/Enemies.json
  source/core/assets/configs/defences.json
  source/core/assets/configs/enemies.json
  source/core/assets/images/basic_robot.atlas
  source/core/assets/images/basic_robot.png
  source/core/assets/images/basic_robot_default_sprite.png
  source/core/assets/images/blue_robot.atlas
  source/core/assets/images/blue_robot.png
  source/core/assets/images/blue_robot_default_sprite.png
  source/core/assets/images/red_robot.atlas
  source/core/assets/images/red_robot.png
  source/core/assets/images/red_robot_default_sprite.png
  source/core/src/main/com/csse3200/game/areas/GameArea.java
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/npc/RobotAnimationController.java
  source/core/src/main/com/csse3200/game/components/tasks/MoveLeftTask.java
  source/core/src/main/com/csse3200/game/components/tasks/RobotAttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TeleportTask.java
  source/core/src/main/com/csse3200/game/entities/EntitySpawn.java
  source/core/src/main/com/csse3200/game/entities/WaveManager.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/configs/TeleportRobotConfig.java
  source/core/src/main/com/csse3200/game/entities/factories/DefenceFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/RobotFactory.java
  source/core/src/main/com/csse3200/game/physics/components/ColliderComponent.java
  source/core/src/test/com/csse3200/game/areas/LevelGameAreaTest.java
  source/core/src/test/com/csse3200/game/areas/SpawnRobotTest.java
  source/core/src/test/com/csse3200/game/components/tasks/MoveLeftTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/TeleportTaskTest.java
  source/core/src/test/com/csse3200/game/entities/EntitySpawnTest.java
  source/core/src/test/com/csse3200/game/entities/factories/RobotFactoryTest.java
  source/core/src/test/com/csse3200/game/tile/TileTest.java
Labels: enhancement, sprint 2, team 6

#199 PR Drag and Drop functionaly from task/DragandDropExtension into feature branch feat/levels
  source/core/src/main/com/csse3200/game/areas/AreaAPI.java
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/DeckInputComponent.java
  source/core/src/main/com/csse3200/game/components/hotbar/HotbarDisplay.java
  source/core/src/main/com/csse3200/game/components/tile/TileInputComponent.java
  source/core/src/main/com/csse3200/game/ui/DragOverlay.java
  source/core/src/test/com/csse3200/game/components/tile/TileInputComponentTest.java
Labels: sprint 2, team 7

#202 (#166) Hotbar clean and tile test coverage increased
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/hotbar/HotbarDisplay.java
  source/core/src/test/com/csse3200/game/tile/TileHitboxComponentTest.java
  source/core/src/test/com/csse3200/game/tile/TileStorageComponentTest.java
Labels: sprint 2, team 7

#203 (#115) Config file and class to be used in LevelGameArea
  source/core/assets/configs/levels.json
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseLevelGameConfig.java
  source/core/src/test/com/csse3200/game/areas/LevelGameAreaTest.java
Labels: sprint 2, team 7

#184 Defenses: Projectiles and Furnace
  source/core/assets/configs/Defences.json
  source/core/assets/images/forge_1.png
  source/core/assets/images/scrap_metal.png
  source/core/assets/images/sling_projectile.png
  source/core/assets/images/sling_projectile_pad.png
  source/core/assets/images/sling_shooter.atlas
  source/core/src/main/com/csse3200/game/areas/ForestGameArea.java
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/components/CombatStatsComponent.java
  source/core/src/main/com/csse3200/game/components/DefenderStatsComponent.java
  source/core/src/main/com/csse3200/game/components/GeneratorStatsComponent.java
  source/core/src/main/com/csse3200/game/components/TouchAttackComponent.java
  source/core/src/main/com/csse3200/game/components/currency/Currency.java
  source/core/src/main/com/csse3200/game/components/currency/CurrencyGeneratorComponent.java
  source/core/src/main/com/csse3200/game/components/currency/ScrapComponent.java
  source/core/src/main/com/csse3200/game/components/currency/ScrapHudDisplay.java
  source/core/src/main/com/csse3200/game/components/dossier/DossierManager.java
  source/core/src/main/com/csse3200/game/components/projectiles/MoveRightComponent.java
  source/core/src/main/com/csse3200/game/components/tasks/AttackTask.java
  source/core/src/main/com/csse3200/game/components/tasks/IdleTask.java
  source/core/src/main/com/csse3200/game/components/tasks/TargetDetectionTasks.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseDefenceConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseDefenderConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseGeneratorConfig.java
  source/core/src/main/com/csse3200/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/csse3200/game/entities/factories/DefenceFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ProjectileFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/ScrapFactory.java
  source/core/src/main/com/csse3200/game/entities/factories/SunlightFactory.java
  source/core/src/main/com/csse3200/game/screens/MainGameScreen.java
  source/core/src/main/com/csse3200/game/services/ConfigService.java
  source/core/src/main/com/csse3200/game/services/CurrencyService.java
  source/core/src/test/com/csse3200/game/components/DefenderStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/GeneratorStatsComponentTest.java
  source/core/src/test/com/csse3200/game/components/currency/CurrencyTest.java
  source/core/src/test/com/csse3200/game/components/dossier/DossierBackendTest.java
  source/core/src/test/com/csse3200/game/components/tasks/AttackTaskTest.java
  source/core/src/test/com/csse3200/game/components/tasks/IdleTaskTest.java
  source/core/src/test/com/csse3200/game/services/CurrencyServiceTest.java
Labels: enhancement, sprint 2, team 2

#210 Added deselection functionality to click drag and click drop
  source/core/src/main/com/csse3200/game/components/hotbar/HotbarDisplay.java
  source/core/src/test/com/csse3200/game/areas/LevelGameAreaTest.java
Labels: sprint 2, team 7

#212 (#113) PR 3/3 for Feat/levels
  ai/team7.md
  source/core/assets/configs/levels.json
  source/core/assets/images/hotbar.png
  source/core/src/main/com/csse3200/game/areas/AreaAPI.java
  source/core/src/main/com/csse3200/game/areas/LevelGameArea.java
  source/core/src/main/com/csse3200/game/areas/terrain/MapFactory.java
  source/core/src/main/com/csse3200/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/csse3200/game/components/DeckInputComponent.java
  source/core/src/main/com/csse3200/game/components/hotbar/HotbarDisplay.java
  source/core/src/main/com/csse3200/game/components/tile/TileInputComponent.java
  source/core/src/main/com/csse3200/game/entities/configs/BaseLevelGameConfig.java
  source/core/src/main/com/csse3200/game/ui/DragOverlay.java
  source/core/src/test/com/csse3200/game/areas/LevelGameAreaTest.java
  source/core/src/test/com/csse3200/game/components/tile/TileInputComponentTest.java
  source/core/src/test/com/csse3200/game/tile/TileHitboxComponentTest.java
  source/core/src/test/com/csse3200/game/tile/TileStorageComponentTest.java
  source/core/src/test/com/csse3200/game/ui/DragOverlayTest.java
Labels: enhancement, sprint 2, team 7

#215 [Bug fix] Ensure level completion condition met
  source/core/src/main/com/csse3200/game/entities/WaveManager.java
Labels: bug, sprint 2, team 5

#217 fixed time update issue in lanerunner game
  source/core/src/main/com/csse3200/game/screens/LaneRunnerScreen.java
Labels: bug, sprint 2, team 3
